### ISSUE TITLE
Tyk's Tile on DD dashboard is not showing up

### ISSUE THREAD

**Issue by letzya** [DataDog/integrations-extras#1074]
Hi,
Tyk's PR has been merged to this repo and now is visible on the DD's [website](https://docs.datadoghq.com/integrations/tyk/#pagetitle). 
My question is why can't I see it also under `integration` in DD dashboard?

**Comment by yzhan289** [comment]
Hi @letzya , apologies for the delay. We are working on syncing Tyk in DD app. There was an issue in your `manifest.json` file with `author`. You have that field as a string, but it should be a dictionary, see here for an example: https://github.com/DataDog/integrations-extras/blob/master/rookout/manifest.json#L37-L41. Another option is just to remove the field, since it is an optional field for V1 manifests. I made a PR removing `author`, so if you approve of this change we can apply it: https://github.com/DataDog/integrations-extras/pull/1075.

**Comment by yzhan289** [comment]
Hi @letzya , we have merged and applied the changes from the PR. Can you check your Datadog again to verify that Tyk is showing up? To see the Tyk dashboard, you will need to first install the Tyk tile under the `Integrations` tab.
![image](https://user-images.githubusercontent.com/31313038/144915720-f718d2b8-1422-48d3-8e0d-7cbc03808f12.png)

**Comment by letzya** [comment]
@yzhan289 thanks for reaching out. I have checked and it's showing.
Can i please ask why only part of the logo is showing up when I open the integration ?

The logo it in  [/tyk/images/tyk_logo_no_bg.png](https://github.com/DataDog/integrations-extras/blob/master/tyk/images/tyk_logo_no_bg.png)

<img width="990" alt="image" src="https://user-images.githubusercontent.com/3155222/145293661-5f9fb4cb-e03f-4569-9ef7-7fe5979165b1.png">

**Comment by yzhan289** [comment]
Hi @letzya , that is intentional. I believe our design team removes the name in the logo when you open the integration. This is the case for our other integrations as well:
![image](https://user-images.githubusercontent.com/31313038/145416626-e0bd5791-c619-4ca2-aa78-7d9c8188e059.png)
![image](https://user-images.githubusercontent.com/31313038/145416652-6657cf7d-0a43-4c2e-b73e-b008d02deff7.png)

**Comment by letzya** [comment]
ok so can I put another image, like this one?
![Tyk_mascot](https://user-images.githubusercontent.com/3155222/145877150-063aa3ce-16d2-495a-87f7-0a7218803af5.png)

**Comment by yzhan289** [comment]
@letzya We will check with our design team and get back to you on that!

**Comment by ChristineTChen** [comment]
Hi @letzya !

I'm taking over this issue from @yzhan289.

Can you provide the same image in SVG format?

**Comment by letzya** [comment]
Is this one okay? [mascot-painted-vector_logo.svg.zip](https://github.com/DataDog/integrations-extras/files/7721209/mascot-painted-vector_logo.svg.zip)

**Comment by ChristineTChen** [comment]
Can you include this in the  tyk/image directory? https://github.com/DataDog/integrations-extras/tree/master/tyk/images. you can open a PR

**Comment by letzya** [comment]
@ChristineTChen I just added the image https://github.com/DataDog/integrations-extras/pull/1108

**Comment by letzya** [comment]
@ChristineTChen Hi, thanks for merging. 
Now that it's merged, when should I expect to see the update? (I'm not really clear how does this actually works). Thanks :)

**Comment by ChristineTChen** [comment]
Hi @letzya 

Our design team has updated the logo and it's currently updated on our staging. It should be visible from our org by EOD.
<img width="909" alt="Screen Shot 2021-12-20 at 3 08 22 PM" src="https://user-images.githubusercontent.com/15065007/146826582-fcb3801d-840b-427d-9f66-35b6d8c6b57c.png">

**Comment by letzya** [comment]
@ChristineTChen thanks. I still can't see it. Will give it another day. thanks
