### ISSUE TITLE
Pod with nvml integration fails to initialise

### ISSUE THREAD

**Issue by swaroop1012** [DataDog/integrations-extras#1833]
Used the below Dockerfile to create an image. Could not use the Dockerfile in this repo as the version of grpcio it was trying to install gave the error `FileNotFoundError: [Errno 2] No such file or directory: 'cc'`

```
FROM gcr.io/datadoghq/agent:latest
RUN agent integration install -t -r datadog-nvml==1.0.6

RUN pip install pynvml==11.4.1 grpcio==1.54.0

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES all
```

**Additional environment details:**
Cloud provider: AWS (EKS)

**Steps to reproduce the issue:**
1. Use the above Dockerfile to create an image
2. Use the Docker image in a daemonset manifest file
3. Deploy the daemonset in an EKS cluster

**Received result:**
The pods created were in a `Init:CrashLoopBackOff` state. There was nothing in the pod events.

**Expected result:**
The pod to go into a running state.

**Additional information you deem important (e.g. issue happens only occasionally):**
N/A

**Comment by swaroop1012** [comment]
In case someone's encountering this issue, I was trying to run an arm64 image on an amd64 node. Building the image with the `--platform` flag fixed it `docker buildx build --platform linux/amd64`.

**Comment by brianchan661** [comment]
@swaroop1012 Did your nvml face this [error](https://github.com/DataDog/integrations-extras/issues/1773)?
I successfully built the image with your command, pods is health, but the datadog-nvml is not running due to the error above. 

the issue was fixed and merged, but seem it is not released. (1.0.6 is already 6 month ago, and the fix was 2 month ago)
