### ISSUE TITLE
How to write a custom check that requires you to execute that command as root user or sudo ?

### ISSUE THREAD

**Issue by jason354007** [DataDog/integrations-extras#631]
Is it possible to use a command that requires sudo privileges. For example, I have a custom check that uses the command xfs_quota.  If I run the custom script with sudo, it works. But when I run the same script using Datadog check substatus command, it complains about permission denied.

**Comment by hithwen** [comment]
The agent does not run with sudo privileges, you would need to change this for it to be able to run privileged commands either by changing the privileges of the `dd-agent` user or by changing the user used to run the agent

**Comment by jason354007** [comment]
We manage the sudo using centrify in our project. So, dd-agent user was granted sudo permissions but it still doesn't solve my problem. For example:

$ sudo su - dd-agent;cat /var/log/messages
This account is currently not available.
cat: /var/log/messages: Permission denied

$ cat /etc/passwd|grep dd-agent
dd-agent:x:995:991:Datadog Agent:/opt/datadog-agent:/sbin/nologin

Is it possible to run cat /var/log/messages using dd-agent user considering it cannot login ?

**Comment by FlorianVeaux** [comment]
Hey @jason354007 sorry for the delay

In order to run a command from a dd-agent check with sudo privileges, you should be able to do something like this:
https://github.com/DataDog/integrations-core/blob/75bf7a444809fba1208ac9b28b78599c5c01575e/process/datadog_checks/process/process.py#L240-L241
but make sure that the dd-agent user has passwordless sudo access.

One way to check this would be to first login with the dd-agent user with the following command
`sudo su -s /bin/bash dd-agent`.

And then to run
`sudo cat /var/log/messages`

Hope it helps !
